"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layout/Navbar/Navbar";
import Footer from "@/components/layout/footer/Footer";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import MySessionProvider from "@/providers/MySessionProvider";
import CartContextProvider from "../context/CartContextProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"

    >
      <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
        <MySessionProvider>
          <CartContextProvider>
            <Navbar />

            {children}
            <Footer />
            <Toaster />
          </CartContextProvider>
        </MySessionProvider>

      </body>
    </html>
  );
}
